Python Basics

In [1]:
# Q1. Split this string
# s = "Hi there Class!"
# into a list. 

s = "Hi there Class!"
li = s.split()
li


['Hi', 'there', 'Class!']

In [3]:
# Q2. Given the variables
# planet = "Earth"
# diameter = 12742
# Use .format() to print the following string: 
# The diameter of Earth is 12742 kilometers.

planet = "Earth"
diameter = 12742
print("The diameter of  {} is {} Kilometers".format(planet,diameter))

The diameter of  Earth is 12742 Kilometers


In [5]:
# Q3. Given this nested list, use indexing to grab the word "hello" 
# lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
hello = lst[3][1][2][0]
hello

'hello'

In [7]:
# Q4. Given this nested dictionary grab the word "hello".
# d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
dict_hello = d['k1'][3]['tricky'][3]['target'][3]
dict_hello

'hello'

In [6]:
# Q5. Create a function that grabs the email website domain from a string in the form: 
# user@domain.com
def grab_domain(email):
	domain = email.split("@")[1]
	return domain

grab_domain("USER@Gmail.com")

'Gmail.com'

In [9]:
# Q6. Create a basic function that returns True if the word 'dog' is contained in the input string

def trueDog(input):
	li = input.split()
	if "dog" in li:
		return True
	else : return False

trueDog("I have a dog Dog dog")

True

In [11]:
# Q7. Create a function that counts the number of times the word "dog" occurs in a string.

def countDog(input):
	counter = 0
	for word in input.split():
		if word == "dog":
			counter += 1
	return counter

countDog("I have a dog Dog dog")



2

In [15]:
# Q8. Use lambda expressions and the filter() function to filter out words from a list that don't start with the 
# letter 's'. 
# For example: seq = ['soup','dog','salad','cat','great']

seq = ['soup','dog','salad','cat','great']
result = filter(lambda x : x[0]!= 's',seq)
print(list(result))


['dog', 'cat', 'great']


In [18]:
# Q9. You are driving a little too fast, and a police officer stops you. Write a function to return one of 3 pos
# sible results: "No Challan", "Small Challan", or "Heavy Challan". If your speed is 60 or less, the result is 
# "No Challan". If speed is between 61 and 80 inclusive, the result is "Small Challan". If speed is 81 or mor
# e, the result is "Heavy Challan". Unless it is your birthday (encoded as a Boolean value in the parameters 
# of the function) -- on your birthday, your speed can be 5 higher in all cases.

def caught_speeding(speed, bday):
	if not bday:
		if speed <= 60 :result = "No Challan"
		elif speed >= 61 and speed <= 80 : result = " Small Challan"
		elif speed >= 81 : result = "Heavy Challan"
		else : result = "Error"
	else:
		if speed <= 65 :result = "No Challan"
		elif speed >= 66 and speed <= 85 : result = " Small Challan"
		elif speed >= 86 : result = "Heavy Challan"
		else : result = "Error"
	return result

print(caught_speeding(81,True))
print(caught_speeding(81,False))

 Small Challan
Heavy Challan


In [20]:
# Q10. Concatenate two lists index-wise
# list1 = ["M", "na", "i", "She"] 
# list2 = ["y", "me", "s", "lly"]
# Expected Outcome: ['My', 'name', 'is', 'Shelly']

def concatenate_list(list1,list2):
	final =[]
	for (li1, li2) in zip(list1, list2):
		final.append(li1+li2)
	return final

list1 = ["M", "na", "i", "She"]
list2 = ["y", "me", "s", "lly"]
concatenate_list(list1,list2)

['My', 'name', 'is', 'Shelly']

In [19]:
# Q11. Concatenate two lists in the following order
# list1 = ["Hello ", "take "]
# list2 = ["Dear", "Sir"]
# Expected Output: ['Hello Dear', 'Hello Sir', 'take Dear', 'take Sir']

def concatenate_list_2(list1,list2):
	final = []
	for li1 in list1:
		for li2 in list2:
			final.append(li1+li2)
	return final

list1 = ["Hello ", "take "]
list2 = ["Dear", "Sir"]
concatenate_list_2(list1,list2)

['Hello Dear', 'Hello Sir', 'take Dear', 'take Sir']

In [22]:
# Q12. Add item 7000 after 6000 in the following Python List
# list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
list1

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

In [24]:
# Q13. Given a Python list, remove all occurrence of 20 from the list
# list1 = [5, 20, 15, 20, 25, 50, 20]

def remove_items(test_list, item):
  for i in test_list:
    if(i == item):
      test_list.remove(i)
list1 = [5, 20, 15, 20, 25, 50, 20]
remove_items(list1,20)  
list1    


[5, 15, 25, 50]

In [25]:
# Q14. Check if a value 200 exists in a dictionary
# d1 = {'a': 100, 'b': 200, 'c': 300}

d1 = {'a': 100, 'b': 200, 'c': 300}
for key,value in d1.items():
  if value==200: print("True! value exists")


True! value exists


In [27]:
# Q15. Find the sum of the series 2 +22 + 222 + 2222 + .. n terms

import math
def sumOfSeries( n ):
    return 0.0246 * (math.pow(10, n) - 1 - (9 * n))
    
n = 10
print(sumOfSeries(n))

245999997.7614


Assignment 2

In [30]:
# 1. Create an array of 10 fives

import numpy as np
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [31]:
# 2. Create an array of the integers from 10 to 50

arr = np.array(range(10,51))
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [34]:
# 3. Create an array of all the even integers from 10 to 50

arrall = np.array(range(10,51))
arreven = arrall%2==0
arr = arrall[arreven]
arr

# arr = np.array(range(10,51,2))
# arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [37]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8

matrix = np.arange(0,9).reshape(3,3)
matrix


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
# 5. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

rand_num = np.random.normal(0,1,25)
rand_num

array([-0.11638412,  0.38989635, -0.48794138, -1.14452657, -0.56145157,
        0.86276652, -0.08959469,  0.09986746,  0.17175922, -0.12348868,
        0.68564203,  0.51586084,  0.21190454, -1.10294533, -0.09840684,
       -1.29250479,  0.06334022,  0.69641666, -1.35711256,  0.24896516,
        0.54940365, -0.56770541, -0.10119452,  0.87893494, -2.15673639])

In [43]:
# 6. Create the following array:
# array([0. , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
#  0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
#  0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
#  0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
#  0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
#  0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
#  0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
#  0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
#  0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
#  0.99, 1. ])

arr = np.arange(0,1.01,0.01)
arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [44]:
# 7. Create an array of 20 linearly spaced points between 0 and 1

arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [52]:
# 8. Generate the following matrix, mat, 
# array([[ 1, 2, 3, 4, 5],
#  [ 6, 7, 8, 9, 10],
#  [11, 12, 13, 14, 15],
#  [16, 17, 18, 19, 20],
#  [21, 22, 23, 24, 25]])
# and extract the following using the indexing and slicing:
# array([[12, 13, 14, 15],
#  [17, 18, 19, 20],
#  [22, 23, 24, 25]])
# array([[ 2],[ 7],[12]])

arr = np.arange(1,26).reshape(5,5)
print(arr)

slice1 = arr[2:,1:]
print(slice1)

slice2 = arr[:3,1:2]
print(slice2)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
[[ 2]
 [ 7]
 [12]]


In [58]:
# Get the sum of all the values in mat
print(np.sum(arr))

# Get the sum of all the rows and columns in mat
#rows
print(np.sum(arr,axis=1))
#columns
print(np.sum(arr,axis=0))

325
[ 15  40  65  90 115]
[55 60 65 70 75]
